name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install and Build www
        working-directory: ./www
        run: |
          npm install --verbose
          npm run build

      - name: Restart or Start Fireman WWW
        run: |
          pm2 restart fireman-www || pm2 start "npm start" --name fireman-www

      - name: Verify Fireman WWW Deployment
        run: |
          curl -f http://localhost:3000 || echo "fireman-www failed to start"
